### ISSUE TITLE
virtual-console overrides console.log, even if stdout is not a TTY

### ISSUE THREAD

**Issue by starpit** [kamiyo/multi-progress-bars#10] opened 2021-05-13 15:38 UTC
This is a follow-on bug from #7. I realized that my PR #8 did not fix the fact that virtual-console.ts overrides console.log with logTop/logBottom, even if process.stdout is not a TTY.

**Comment by kamiyo** [comment] 2021-05-18 05:25
Hi, I added a fix into the newest alpha: multi-progress-bars@4.0.0-alpha.0

I didn't merge your PR because I had done a big rewrite of the backend these past weeks, so it's not quite in the same spot. See if the issue is fixed now.

**Closed** 2021-06-30 03:26 UTC
